enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[Music-Morphe]
app-name = "ytm"
rv-brand = "mrph"
build-mode = "both"
arch = "both"
patches-version = "latest"
cli-version = "dev"
version = "9.06.51"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patcher-args = "-e 'Custom branding' -OcustomName=Morphette -e 'Change package name' -OpackageName=vip.dh6k.mrph.m"
